## Sections
- [markdown使用](#markdown使用)
- [公式符号](#公式符号)
- [常见词翻译](#常见词翻译)
- [python知识点](#python知识点)
    - [魔法方法](#魔法方法)
        - [\_\_getitem\_\_](#\_\_getitem\_\_)
        -[\_\_call\_\_](#\_\_call\_\_)
- [numpy](#numpy)
- [PyTorch](#PyTorch)
    - [基础方法](#基础方法)
    - [自动求导](#自动求导)
        - [y.data.norm()](#y.data.norm())
        - [with torch.no_grad()](#with&nbsp;torch.no_grad())
    - [神经网络](#神经网络)  # nn库
        - [nn.Conv2d卷积](#nn.Conv2d卷积)
        - [nn.MaxPool2d](#nn.MaxPool2d)
        - [nn.VagPool2d](#nn.MaxPool2d)
        - [nn.Linear](#nn.Linear)
        - [nn.ReLU&nbsp;vs&nbsp;F.ReLU](#nn.ReLU&nbsp;vs&nbsp;F.ReLU)
    - [torchvision库](#torchvision库)
    
    
 [back to bottom](#Bottom)

# markdown使用
- [jupyter notebook中markdown使用](https://www.jianshu.com/p/576e3f1049f8)
- [如何在Markdown文档中插入空格?](https://www.cnblogs.com/klchang/p/10203404.html)
- [MarkDown用法详细介绍](https://blog.csdn.net/qq_27229113/article/details/73692171)

[[back to top](#Sections)]

# 公式符号
更多用法：[https://blog.csdn.net/smilejiasmile/article/details/80670742](https://blog.csdn.net/smilejiasmile/article/details/80670742)

J_\alpha(x) = \sum_{m=0}^\infty \frac{(-1)^m}{m! \Gamma (m + \alpha + 1)} {\left({ \frac{x}{2} }\right)}^{2m + \alpha} \text {，行内公式示例}
$$ J_\alpha(x) = \sum_{m=0}^\infty \frac{(-1)^m}{m! \Gamma (m + \alpha + 1)} {\left({ \frac{x}{2} }\right)}^{2m + \alpha} \text {，行内公式示例} $$
\int_0^1 {x^2} \,{\rm d}x
$$\int_0^1 {x^2} \,{\rm d}x$$
\lim_{n \to +\infty} \frac{1}{n(n+1)} \quad and \quad \lim_{x\leftarrow{示例}} \frac{1}{n(n+1)}
$$ \lim_{n \to +\infty} \frac{1}{n(n+1)} \quad and \quad \lim_{x\leftarrow{示例}} \frac{1}{n(n+1)} $$
\sum_{i=1}^n \frac{1}{i^2} \quad and \quad \prod_{i=1}^n \frac{1}{i^2} \quad and \quad \bigcup_{i=1}^{2} R
$$\sum_{i=1}^n \frac{1}{i^2} \quad and \quad \prod_{i=1}^n \frac{1}{i^2} \quad and \quad \bigcup_{i=1}^{2} R$$


[[back to top](#Sections)]

# 常见词翻译

- criterion: 标准
- optim: 使最优化
- optimizer: 最优控制器

# python知识点

[[back to top](#Sections)]

## 魔法方法

[[back to top](#Sections)]

### \_\_getitem\_\_

[python：__getitem__方法详解](https://blog.csdn.net/weixin_42557907/article/details/81589574)

这个方法返回与指定键想关联的值。对序列来说，键应该是0~n-1的整数，其中n为序列的长度。对映射来说，键可以是任何类型。

[[back to top](#Sections)]

In [26]:
class Tag:
    def __init__(self):
        self.change={'python':'This is python'}
 
    def __getitem__(self, item):
        print('这个方法被调用')
        return self.change[item]
 
a=Tag()
print(a['python'])

这个方法被调用
This is python


### \_\_call\_\_
[Python __call__详解](https://www.jianshu.com/p/e1d95c4e1697?utm_source=oschina-app)

``__call__``的作用相当于闭包中的内层方法，可以让一个类的实例对象当成方法调用

[[back to top](#Sections)]

# numpy

[[back to top](#Sections)]

## np.transpose()

多维数组的维度转换

[[back to top](#Sections)]

In [9]:
import numpy as np
# 0,1,2
x = np.arange(12).reshape((2,2,3))
print(x)
# 1,0,2
x = x.transpose(1,0,2)
print(x)
# 2,0,1
x = np.transpose(x, (2,0,1))
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


# PyTorch

目前所有见过的类：
- **torch.Tensor**
    - A multi-dimensional array with support for autograd operations like backward(). Also holds the gradient w.r.t. the tensor.
    - 支持autograd操作(如backward())的多维数组。也保持梯度w.r.t张量。
- **nn.Module**
    - Neural network module. Convenient way of encapsulating parameters, with helpers for moving them to GPU, exporting, loading,etc.
    - 神经网络模块。方便的封装参数的方式，有帮助移动他们到GPU，导出，加载等。
- **nn.Parameter** 
    - A kind of Tensor, that is automatically registered as a parameter when assigned as an attribute to a Module.
    - 一种张量，当被指定为模块的属性时，自动作为参数注册。
- **autograd.Function** 
    - Implements forward and backward definitions of an autograd operation. Every Tensor operation, creates at least a single Function node, that connects to functions thatcreated a Tensor and encodes its history.
    - 实现autograd操作的向前和向后定义。每个张量操作，至少创建一个函数节点，连接到创建一个张量并编码其历史的函数。

[[back to top](#Sections)]

## 基础方法

[[back to top](#Sections)]

**目前见到的一些方法的使用，仅展示，未整理：**  
<font color=red>注：行与行之间没有关联，一般开头的变量都是一个张量，同名变量意义大部分情况相同</font>
```python
dtype = torch.float
# 切换CPU、GPU
device = torch.device("cpu")
device = torch.device("cuda: 0") 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.randn(64, 100, device=device, dtype=dtype)  # 随机数据
w = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)
h = x.mm(w1)
h_relu = h.clamp(min=0)
loss = (y_pred - y).pow(2).sum()
loss.item()
h_relu.t()
grad_h_relu.clone()
grad_h[h < 0] = 0
loss.backward()
with torch.no_grad():
w1.grad.zero_()
```

## 自动求导

### y.data.norm() 
y的L2范数：$\sum_{i=1}^ny^2$

[[back to top](#Sections)]

In [4]:
import torch
x = torch.randn(3, requires_grad=True)
y = x*2
print(y.data.norm())
print(torch.sqrt(torch.sum(torch.pow(y,2))))  #其实就是对y张量L2范数，先对y中每一项取平方，之后累加，最后取根号
i=0
while y.data.norm()<1000:
  y = y*2
  i+=1
print(y)
print(i)

tensor(4.3757)
tensor(4.3757, grad_fn=<SqrtBackward>)
tensor([-947.1443, -188.2073,  567.7290], grad_fn=<MulBackward0>)
8


### with&nbsp;torch.no_grad()
[https://www.jianshu.com/p/1cea017f5d11](https://www.jianshu.com/p/1cea017f5d11)  
作用：使由requires_grad = True的tensor生成的新tensor的requires_grad=False，gead_fn=None,即不会对新tensor求导。

[[back to top](#Sections)]

In [5]:
import torch

x = torch.randn(10, 5, requires_grad = True)
y = torch.randn(10, 5, requires_grad = True)
z = torch.randn(10, 5, requires_grad = True)
with torch.no_grad():
    w = x + y + z
    print(w.requires_grad)
    print(w.grad_fn)
print(w.requires_grad)

False
None
False


## 神经网络

神经网络可以通过 **torch.nn** 包来构建。

现在对于自动梯度(**autograd**)有一些了解，神经网络是基于自动梯度 (autograd)来定义一些模型。一个 **nn.Module** 包括层和一个方法 **forward(input)** 它会返回输出(**output**)。

一个典型的神经网络训练过程包括以下几点：
1. 定义一个包含可训练参数的神经网络
2. 迭代整个输入
3. 通过神经网络处理输入
4. 计算损失(loss)
5. 反向传播梯度到神经网络的参数
6. 更新网络的参数，典型的用一个简单的更新方法：weight = weight - learning_rate *gradient

In [2]:
import torch.nn as nn

[[back to top](#Sections)]

### nn.Conv2d卷积

[[back to top](#Sections)]

一维卷积与二维卷积: [https://blog.csdn.net/qq_26369907/article/details/88366147](https://blog.csdn.net/qq_26369907/article/details/88366147)
- **nn.Conv1d**: 一维的卷积能处理多维数据
- **nn.Conv2d**: 二维卷积可以处理二维数据

nn.Conv2d(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True))  
nn.Conv1d(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True))  
**参数**：
- **in_channel**:　输入数据的通道数，例RGB图片通道数为3；
- **out_channel**: 输出数据的通道数，这个根据模型调整；
- **kennel_size**: 卷积核大小，可以是int，或tuple；kennel_size=2,意味着卷积大小(2,2)， kennel_size=（2,3），意味着卷积大小（2，3）即非正方形卷积
- **stride**：步长，默认为1，与kennel_size类似，stride=2,意味着步长上下左右扫描皆为2， stride=（2,3），左右扫描步长为2，上下为3；
- **padding**：零填充


**卷积计算过程**：  
h/w = (h/w - kennel_size + 2padding) / stride + 1  
x = ([10,16,30,32]),其中h=30,w=32,对于卷积核长分别是 h:3，w:2 ；对于步长分别是h：2，w:1；padding默认0；  
h = (30 - 3 + 20)/ 2 +1 = 27/2 +1 = 13+1 =14  
w =(32 - 2 + 2*0)/ 1 +1 = 30/1 +1 = 30+1 =31  
batch = 10, out_channel = 33  
故： y= ([10, 33, 14, 31])

#### 例：nn.Conv1d

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.randn(10, 16, 30, 32, 34)
# batch, channel , height , width
print(x.shape)
class Net_1D(nn.Module):
    def __init__(self):
        super(Net_1D, self).__init__()
        self.layers = nn.Sequential(
            nn.Conv1d(in_channels=16, out_channels=16, kernel_size=(3, 2, 2), stride=(2, 2, 1), padding=[2,2,2]),
            nn.ReLU()
        )
    def forward(self, x):
        output = self.layers(x)
        log_probs = F.log_softmax(output, dim=1)
        return  log_probs

n = Net_1D()  # in_channel,out_channel,kennel,
print(n)
y = n(x)
print(y.shape)

torch.Size([10, 16, 30, 32, 34])
Net_1D(
  (layers): Sequential(
    (0): Conv1d(16, 16, kernel_size=(3, 2, 2), stride=(2, 2, 1), padding=[2, 2, 2])
    (1): ReLU()
  )
)
torch.Size([10, 16, 16, 18, 37])


#### 例：nn.Conv2d

In [3]:
import torch
import torch.nn as nn

x = torch.randn(10, 16, 30, 32) # batch, channel , height , width
print(x.shape)
m = nn.Conv2d(16, 33, (3, 2), (2,1))  # in_channel, out_channel ,kennel_size,stride
print(m)
y = m(x)
print(y.shape)

torch.Size([10, 16, 30, 32])
Conv2d(16, 33, kernel_size=(3, 2), stride=(2, 1))
torch.Size([10, 33, 14, 31])


### nn.MaxPool2d
[https://www.jianshu.com/p/9d93a3391159](https://www.jianshu.com/p/9d93a3391159)


class torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False)  
**nn.Avg_pool**: 对于Avg_pool来说，参数和Max_pool是完全相同的，主要区别就是在kernel中取的是平均值操作。

参数：
- kernel_size(int or tuple): max pooling的窗口大小，
- stride(int or tuple, optional): max pooling的窗口移动的步长。默认值是kernel_size
- padding(int or tuple, optional): 输入的每一条边补充0的层数
- dilation(int or tuple, optional): 一个控制窗口中元素步幅的参数
- return_indices: 如果等于True，会返回输出最大值的序号，对于上采样操作会有帮助
- ceil_mode: 如果等于True，计算输出信号大小的时候，会使用向上取整，代替默认的向下取整的操作

[[back to top](#Sections)]

<img src="learn_img/16715697-3d69c563031e9ec4.webp" width="50%"/>

In [17]:
import torch
import torch.nn as nn
a = torch.randn(3,5,10)
b = nn.MaxPool2d((5,1))  # kernel = 5 步长为1
c = b(a)
c.shape

torch.Size([3, 1, 10])

In [18]:
# pool操作并不改变张量的通道数
x = torch.rand(1,3,7,7)
out = nn.MaxPool2d(kernel_size=2,stride=2)
out.forward(x).shape

torch.Size([1, 3, 3, 3])

In [21]:
x = torch.rand(1,3,7,7)
out = nn.AvgPool2d(kernel_size=2,stride=2)
out.forward(x).shape

torch.Size([1, 3, 3, 3])

### nn.Linear
[https://blog.csdn.net/qq_42079689/article/details/102873766](https://blog.csdn.net/qq_42079689/article/details/102873766)  
更详细：[https://blog.csdn.net/weixin_44613063/article/details/90274590](https://blog.csdn.net/weixin_44613063/article/details/90274590)

PyTorch的 **nn.Linear()** 是用于设置网络中的全连接层的，需要注意的是全连接层的输入与输出都是二维张量，一般形状为\[batch_size, size\]
$$y=xA^T+b$$

计算步骤：
```python
@weak_script_method
def forward(self, input):
    return F.linear(input, self.weight, self.bias) 
```
返回的是：**input * weight + bias**

[[back to top](#Sections)]

In [24]:
import torch
from torch import nn

# in_features由输入张量的形状决定，out_features则决定了输出张量的形状 
connected_layer = nn.Linear(in_features = 64*64*3, out_features = 1)

# 假定输入的图像形状为[64,64,3]
input = torch.randn(1,64,64,3)

# 将四维张量转换为二维张量之后，才能作为全连接层的输入
input = input.view(1,64*64*3)
print(input.shape)
output = connected_layer(input) # 调用全连接层
print(output.shape)

torch.Size([1, 12288])
torch.Size([1, 1])


### nn.ReLU&nbsp;vs&nbsp;F.ReLU
[https://blog.csdn.net/u011501388/article/details/86602275](https://blog.csdn.net/u011501388/article/details/86602275)

在如下网络中，AlexNet_1与AlexNet_2实现的结果是一致的，但是可以看到将ReLU层添加到网络有两种不同的实现，即nn.ReLU和F.ReLU两种实现方法。
其中nn.ReLU作为一个层结构，必须添加到nn.Module容器中才能使用，而F.ReLU则作为一个函数调用，看上去作为一个函数调用更方便更简洁。具体使用哪种方式，取决于编程风格。在PyTorch中,nn.X都有对应的函数版本F.X，但是并不是所有的F.X均可以用于forward或其它代码段中，因为当网络模型训练完毕时，在存储model时，在forward中的F.X函数中的参数是无法保存的。也就是说，在forward中，使用的F.X函数一般均没有状态参数，比如F.ReLU，F.avg_pool2d等，均没有参数，它们可以用在任何代码片段中。

[[back to top](#Sections)]

In [25]:
import torch.nn as nn
import torch.nn.functional as F
import torch.nn as nn
 
class AlexNet_1(nn.Module):
 
    def __init__(self, num_classes=n):
        super(AlexNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
         )
 
    def forward(self, x):
        x = self.features(x)
 
class AlexNet_2(nn.Module):
 
    def __init__(self, num_classes=n):
        super(AlexNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(64),
         )
 
    def forward(self, x):
        x = self.features(x)
        x = F.ReLU(x)

### torchvision库

torchvision库简介（翻译）: [https://www.cnblogs.com/yjphhw/p/9773333.html](https://www.cnblogs.com/yjphhw/p/9773333.html)  
torchvision是独立于pytorch的关于图像操作的一些方便工具库。  
torchvision的详细介绍在：[https://pypi.org/project/torchvision/](https://pypi.org/project/torchvision/)  
torchvision主要包括一下几个包：  
- vision.datasets : 几个常用视觉数据集，可以下载和加载，这里主要的高级用法就是可以看源码如何自己写自己的Dataset的子类
- vision.models : 流行的模型，例如 AlexNet, VGG, ResNet和Densenet以及 与训练好的参数。
- vision.transforms : 常用的图像操作，例如：随机切割，旋转，数据类型转换，图像到tensor,numpy数组到tensor,tensor到图像等。
- vision.utils : 用于把形似 (3 x H x W) 的张量保存到硬盘中，给一个mini-batch的图像可以产生一个图像格网。

[[back to top](#Sections)]

## Bottom
[[back to top](#Sections)]