## Sections
- [markdown使用](#markdown使用)
- [公式符号](#公式符号)
- [常见词翻译](#常见词翻译)
- [机器学习知识](#机器学习知识)
- [python知识点](#python知识点)
    - [魔法方法](#魔法方法)
        - [\_\_getitem\_\_](#\_\_getitem\_\_)
        -[\_\_call\_\_](#\_\_call\_\_)
    - [copy.deepcopy()](#copy.deepcopy())
- [numpy](#numpy)
- [pillow](#pillow)
- [PyTorch](#PyTorch)
    - [基础方法](#基础方法)
        - [torch.clamp](#torch.clamp)
        - [torch.set_grad_enabled()](#torch.set_grad_enabled())
        - [torch.randperm()](#torch.randperm())
    - [自动求导](#自动求导)
        - [y.data.norm()](#y.data.norm())
        - [with torch.no_grad()](#with&nbsp;torch.no_grad())
    - [神经网络](#神经网络)  # torch.nn
        - [nn.Module](#nn.Module)
            - [model.state_dict()](#model.state_dict())
            - [model.train()与model.eval()](#model.train()与model.eval())
        - [nn.Conv2d卷积](#nn.Conv2d卷积)
        - [nn.MaxPool2d](#nn.MaxPool2d)
        - [nn.VagPool2d](#nn.MaxPool2d)
        - [nn.Linear](#nn.Linear)
        - [nn.ReLU&nbsp;vs&nbsp;F.ReLU](#nn.ReLU&nbsp;vs&nbsp;F.ReLU)
        - [nn.functional as F](#nn.functional)
    - [优化器库](#优化器库)  # torch.optim
        - [optim.SGD()](#optim.SGD())
        - [optim.lr_scheduler](#optim.lr_scheduler)
        - [.step()](#.step())
- [torchvision库](#torchvision库)
    - [torchvision.datasets](#torchvision.datasets)
    - [torchvision.models](#torchvision.models)
    - [torchvision.transforms](#torchvision.transforms)
        - [transforms.Compose()](#transforms.Compose)
        - [transforms.ToTensor() and transforms.Normalize()](#transforms.ToTensor())

[back to bottom](#Bottom)

# markdown使用
- [jupyter notebook中markdown使用](https://www.jianshu.com/p/576e3f1049f8)
- [如何在Markdown文档中插入空格?](https://www.cnblogs.com/klchang/p/10203404.html)
- [MarkDown用法详细介绍](https://blog.csdn.net/qq_27229113/article/details/73692171)

[[back to top](#Sections)]

# 公式符号
更多用法：[https://blog.csdn.net/smilejiasmile/article/details/80670742](https://blog.csdn.net/smilejiasmile/article/details/80670742)

J_\alpha(x) = \sum_{m=0}^\infty \frac{(-1)^m}{m! \Gamma (m + \alpha + 1)} {\left({ \frac{x}{2} }\right)}^{2m + \alpha} \text {，行内公式示例}
$$ J_\alpha(x) = \sum_{m=0}^\infty \frac{(-1)^m}{m! \Gamma (m + \alpha + 1)} {\left({ \frac{x}{2} }\right)}^{2m + \alpha} \text {，行内公式示例} $$
\int_0^1 {x^2} \,{\rm d}x
$$\int_0^1 {x^2} \,{\rm d}x$$
\lim_{n \to +\infty} \frac{1}{n(n+1)} \quad and \quad \lim_{x\leftarrow{示例}} \frac{1}{n(n+1)}
$$ \lim_{n \to +\infty} \frac{1}{n(n+1)} \quad and \quad \lim_{x\leftarrow{示例}} \frac{1}{n(n+1)} $$
\sum_{i=1}^n \frac{1}{i^2} \quad and \quad \prod_{i=1}^n \frac{1}{i^2} \quad and \quad \bigcup_{i=1}^{2} R
$$\sum_{i=1}^n \frac{1}{i^2} \quad and \quad \prod_{i=1}^n \frac{1}{i^2} \quad and \quad \bigcup_{i=1}^{2} R$$


[[back to top](#Sections)]

# 常见词翻译

- accuracy - n.**精确度**，准确性
- affine - adj. （数）**仿射的**; n. 姻亲
    - 图像缩放，移动，旋转等可以用一个仿射模型表示
- bias - n. 偏见；偏爱；斜纹；乖离率; vt. 使存偏见; adj. 偏斜的; adv. 偏斜地;
- correct - **修正、调整（数据）**
    - adj. （政治或思想）正确的；恰当的；端正的
    - v. 改正；批改（学生作业）；校正；指出错误；抵消；校准（仪器）；修正、调整（数据）
- criterion - 标准
- device - n. 装置；策略；图案；设备；**终端**
- dropout - 失学儿童；退学；信号丢失；辍学者
    - **在神经网络中为避免数据量过少时造成的过拟合，在训练模型时加入的随机扰动，一般方法是，训练时随机的将一些链路上的训练结果设置为0**
- embedding - **嵌入式**；嵌入；嵌入层；包埋
- epoch - n. \[地质\] 世；新纪元；新时代；**时间上的一点**(在这里指代训练时的一个时刻，训练的某一次迭代)
- hidden - 隐藏；隐蔽性；隐忧；不可告人
    - **隐含层（神经网络）**
- inception - n. **起初**；获得学位；盗梦空间；全面启动；潜行凶间；奠基
- optim - 使最优化
- optimizer - 最优控制器
- validation - 确认；**验证**；校验；检验
- stride - **步幅**；大步走；跨跃弹奏法

## 机器学习知识
- [【卷积神经网络】卷积层，池化层，全连接层](https://blog.csdn.net/idwtwt/article/details/87567432)
- [【深度学习】多通道图像卷积过程及计算方式](https://blog.csdn.net/briblue/article/details/83063170)
    - 滤波器: 使卷积过程中通道数变化的罪魁祸首
    - [科普-深度学习中的卷积-卷积核和滤波器的区别](https://www.cnblogs.com/elitphil/p/12040671.html)

# python知识点
## 魔法方法

[[back to top](#Sections)]

### \_\_getitem\_\_

[python：__getitem__方法详解](https://blog.csdn.net/weixin_42557907/article/details/81589574)

这个方法返回与指定键想关联的值。对序列来说，键应该是0~n-1的整数，其中n为序列的长度。对映射来说，键可以是任何类型。

[[back to top](#Sections)]

In [26]:
class Tag:
    def __init__(self):
        self.change={'python':'This is python'}
 
    def __getitem__(self, item):
        print('这个方法被调用')
        return self.change[item]
 
a=Tag()
print(a['python'])

这个方法被调用
This is python


### \_\_call\_\_
[Python __call__详解](https://www.jianshu.com/p/e1d95c4e1697?utm_source=oschina-app)

``__call__``的作用相当于闭包中的内层方法，可以让一个类的实例对象当成方法调用

[[back to top](#Sections)]

### copy.deepcopy()
深度拷贝

[python中copy()和deepcopy()详解](https://blog.csdn.net/u010712012/article/details/79754132)

[[back to top](#Sections)]

In [4]:
import copy
a = [1,2,3]
b = [a, a]
c = b
d = copy.deepcopy(b)
a[0] = 4
print(c)
print(d)

[[4, 2, 3], [4, 2, 3]]
[[1, 2, 3], [1, 2, 3]]


# numpy

[[back to top](#Sections)]

### np.unique()
该函数是去除数组中的重复数字，并进行排序之后输出。

In [12]:
import numpy as np
a = np.array([2,3,4,1,1,1,2])
b = np.array([[1,2,4],[1,1,3,2]])
print(np.unique(a))
print(np.unique(b))

[1 2 3 4]
[list([1, 1, 3, 2]) list([1, 2, 4])]


### np.where()

In [19]:
import numpy as np

print(np.where(np.array([True, False, False, True])))
print(np.where([False, True, False, False, True]))

(array([0, 3], dtype=int64),)
(array([1, 4], dtype=int64),)


### np.transpose()

多维数组的维度转换

[[back to top](#Sections)]

In [9]:
import numpy as np
# 0,1,2
x = np.arange(12).reshape((2,2,3))
print(x)
# 1,0,2
x = x.transpose(1,0,2)
print(x)
# 2,0,1
x = np.transpose(x, (2,0,1))
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


### np.clip()
[Numpy clip函数](https://www.jianshu.com/p/c36bdac9c4b0)

clip这个函数将将数组中的元素限制在a_min, a_max之间，大于a_max的就使得它等于 a_max，小于a_min,的就使得它等于a_min。

In [3]:
import numpy as np
x=np.array([1,2,3,5,6,7,8,9])
np.clip(x,3,8)

array([3, 3, 3, 5, 6, 7, 8, 8])

# pillow
[Python图像库PIL的类Image及其方法介绍](https://blog.csdn.net/leemboy/article/details/83792729)

[[back to top](#Sections)]

# PyTorch

目前所有见过的类：
- **torch.Tensor**
    - A multi-dimensional array with support for autograd operations like backward(). Also holds the gradient w.r.t. the tensor.
    - 支持autograd操作(如backward())的多维数组。也保持梯度w.r.t张量。
- **nn.Module**
    - Neural network module. Convenient way of encapsulating parameters, with helpers for moving them to GPU, exporting, loading,etc.
    - 神经网络模块。方便的封装参数的方式，有帮助移动他们到GPU，导出，加载等。
- **nn.Parameter** 
    - A kind of Tensor, that is automatically registered as a parameter when assigned as an attribute to a Module.
    - 一种张量，当被指定为模块的属性时，自动作为参数注册。
- **autograd.Function** 
    - Implements forward and backward definitions of an autograd operation. Every Tensor operation, creates at least a single Function node, that connects to functions thatcreated a Tensor and encodes its history.
    - 实现autograd操作的向前和向后定义。每个张量操作，至少创建一个函数节点，连接到创建一个张量并编码其历史的函数。

[[back to top](#Sections)]

## 基础方法

[[back to top](#Sections)]

**目前见到的一些方法的使用，仅展示，未整理：**  
<font color=red>注：行与行之间没有关联，一般开头的变量都是一个张量，同名变量意义大部分情况相同</font>
```python
dtype = torch.float
x = torch.randn(64, 100, device=device, dtype=dtype)  # 随机数据
w = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)
h = x.mm(w1)
h_relu = h.clamp(min=0)
loss = (y_pred - y).pow(2).sum()
loss.item()
h_relu.t()
grad_h_relu.clone()
grad_h[h < 0] = 0
loss.backward()
with torch.no_grad():
w1.grad.zero_()
```

**切换CPU、GPU**
```python
device = torch.device("cpu")
device = torch.device("cuda: 0") 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
```
**加载模型**
```python
checkpoint = torch.load(loadFilename, map_location=torch.device('cpu'))
```
**初始化参数**
```python
embedding_sd = checkpoint['embedding']
embedding.load_state_dict(embedding_sd)
```

### torch.clamp
[https://blog.csdn.net/qq_21997625/article/details/90717359](https://blog.csdn.net/qq_21997625/article/details/90717359)  

**`torch.clamp(input, min, max, out=None)`**  
将输入input张量每个元素的范围限制到区间 [min,max]，返回结果到一个新张量。
- input (Tensor) – 输入张量
- min (Number) – 限制范围下限
- max (Number) – 限制范围上限
- out (Tensor, optional) – 输出张量

相当于RuLE激活函数

[[back to top](#Sections)]

In [2]:
import torch
a=torch.randint(low=0,high=10,size=(10,1))
print(a)
a=torch.clamp(a,3,9)
print(a)

tensor([[2],
        [5],
        [8],
        [7],
        [4],
        [1],
        [2],
        [5],
        [5],
        [5]])
tensor([[3],
        [5],
        [8],
        [7],
        [4],
        [3],
        [3],
        [5],
        [5],
        [5]])


#### torch.set_grad_enabled()
[【学习笔记】关于volatile和0.4.0版本后的torch.set_grad_enabled()](https://blog.csdn.net/zzzpy/article/details/88873109)

使用`torch.set_grad_enabled(True|False)`开启/关闭全部梯度，关闭后之后该张量（tensor）就是不可求导的了

[[back to top](#Sections)]

### torch.randperm()

返回一个0到n-1的数组

In [1]:
import torch
a = torch.randperm(10)
a

tensor([4, 8, 2, 5, 1, 6, 0, 7, 3, 9])

In [2]:
a.tolist()

[4, 8, 2, 5, 1, 6, 0, 7, 3, 9]

## 自动求导

### y.data.norm() 
y的L2范数：$\sum_{i=1}^ny^2$

[[back to top](#Sections)]

In [4]:
import torch
x = torch.randn(3, requires_grad=True)
y = x*2
print(y.data.norm())
print(torch.sqrt(torch.sum(torch.pow(y,2))))  #其实就是对y张量L2范数，先对y中每一项取平方，之后累加，最后取根号
i=0
while y.data.norm()<1000:
  y = y*2
  i+=1
print(y)
print(i)

tensor(4.3757)
tensor(4.3757, grad_fn=<SqrtBackward>)
tensor([-947.1443, -188.2073,  567.7290], grad_fn=<MulBackward0>)
8


### with&nbsp;torch.no_grad()
[https://www.jianshu.com/p/1cea017f5d11](https://www.jianshu.com/p/1cea017f5d11)  
作用：使由requires_grad = True的tensor生成的新tensor的requires_grad=False，gead_fn=None,即不会对新tensor求导。

[[back to top](#Sections)]

In [5]:
import torch

x = torch.randn(10, 5, requires_grad = True)
y = torch.randn(10, 5, requires_grad = True)
z = torch.randn(10, 5, requires_grad = True)
with torch.no_grad():
    w = x + y + z
    print(w.requires_grad)
    print(w.grad_fn)
print(w.requires_grad)

False
None
False


## 神经网络

神经网络可以通过 **torch.nn** 包来构建。

现在对于自动梯度(**autograd**)有一些了解，神经网络是基于自动梯度 (autograd)来定义一些模型。一个 **nn.Module** 包括层和一个方法 **forward(input)** 它会返回输出(**output**)。

一个典型的神经网络训练过程包括以下几点：
1. 定义一个包含可训练参数的神经网络
2. 迭代整个输入
3. 通过神经网络处理输入
4. 计算损失(loss)
5. 反向传播梯度到神经网络的参数
6. 更新网络的参数，典型的用一个简单的更新方法：weight = weight - learning_rate *gradient

In [2]:
import torch.nn as nn

[[back to top](#Sections)]

#### nn.Module
Torch自定义模型需要通过继承该类实现

[pytorch教程之nn.Module类详解——使用Module类来自定义网络层](https://blog.csdn.net/qq_27825451/article/details/90705328)

[[back to top](#Sections)]

##### model.state_dict()
[【PyTorch】state_dict详解](https://blog.csdn.net/bigFatCat_Tom/article/details/90722261)

在pytorch中，torch.nn.Module模块中的state_dict变量存放训练过程中需要学习的权重和偏执系数，state_dict作为python的字典对象将每一层的参数映射成tensor张量，需要注意的是torch.nn.Module模块中的state_dict只包含卷积层和全连接层的参数，当网络中存在batchnorm时，例如vgg网络结构，torch.nn.Module模块中的state_dict也会存放batchnorm's running_mean。

##### model.train()与model.eval()

[model.train()与model.eval()的用法](https://blog.csdn.net/Qy1997/article/details/106455717)  
[Batch Normalization](https://www.cnblogs.com/hutao722/p/9842199.html)  
[Dropout VS Batch Normalization? 是时候放弃Dropout了](https://www.cnblogs.com/hutao722/p/9946047.html)

如果模型中有BN层(Batch Normalization）和Dropout，需要在训练时添加model.train()，在测试时添加model.eval()。其中model.train()是保证BN层用每一批数据的均值和方差，而model.eval()是保证BN用全部训练数据的均值和方差；而对于Dropout，model.train()是随机取一部分网络连接来训练更新参数，而model.eval()是利用到了所有网络连接。

#### nn.Conv2d卷积

[[back to top](#Sections)]

一维卷积与二维卷积: [https://blog.csdn.net/qq_26369907/article/details/88366147](https://blog.csdn.net/qq_26369907/article/details/88366147)
- **nn.Conv1d** - 一维的卷积能处理多维数据
- **nn.Conv2d** - 二维卷积可以处理二维数据

nn.Conv2d(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True))  
nn.Conv1d(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True))  
**参数**：
- **in_channel** - 输入数据的通道数，例RGB图片通道数为3；
- **out_channel** - 输出数据的通道数，这个根据模型调整；
- **kennel_size** - 卷积核大小，可以是int，或tuple；kennel_size=2,意味着卷积大小(2,2)， kennel_size=(2,3)，意味着卷积大小(2,3)即非正方形卷积
- **stride** - 步长，默认为1，与kennel_size类似，stride=2,意味着步长上下左右扫描皆为2， stride=（2,3），左右扫描步长为2，上下为3；
- **padding** - 零填充


**卷积计算过程**：  
h/w = (h/w - kennel_size + 2padding) / stride + 1  
x = ([10,16,30,32]),其中h=30,w=32,对于卷积核长分别是 h:3，w:2 ；对于步长分别是h：2，w:1；padding默认0；  
h = (30 - 3 + 20)/ 2 +1 = 27/2 +1 = 13+1 =14  
w =(32 - 2 + 2*0)/ 1 +1 = 30/1 +1 = 30+1 =31  
batch = 10, out_channel = 33  
故： y= ([10, 33, 14, 31])

#### 例：nn.Conv1d

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.randn(10, 16, 30, 32, 34)
# batch, channel , height , width
print(x.shape)
class Net_1D(nn.Module):
    def __init__(self):
        super(Net_1D, self).__init__()
        self.layers = nn.Sequential(
            nn.Conv1d(in_channels=16, out_channels=16, kernel_size=(3, 2, 2), stride=(2, 2, 1), padding=[2,2,2]),
            nn.ReLU()
        )
    def forward(self, x):
        output = self.layers(x)
        log_probs = F.log_softmax(output, dim=1)
        return  log_probs

n = Net_1D()  # in_channel,out_channel,kennel,
print(n)
y = n(x)
print(y.shape)

torch.Size([10, 16, 30, 32, 34])
Net_1D(
  (layers): Sequential(
    (0): Conv1d(16, 16, kernel_size=(3, 2, 2), stride=(2, 2, 1), padding=[2, 2, 2])
    (1): ReLU()
  )
)
torch.Size([10, 16, 16, 18, 37])


#### 例：nn.Conv2d

In [3]:
import torch
import torch.nn as nn

x = torch.randn(10, 16, 30, 32) # batch, channel , height , width
print(x.shape)
m = nn.Conv2d(16, 33, (3, 2), (2,1))  # in_channel, out_channel ,kennel_size,stride
print(m)
y = m(x)
print(y.shape)

torch.Size([10, 16, 30, 32])
Conv2d(16, 33, kernel_size=(3, 2), stride=(2, 1))
torch.Size([10, 33, 14, 31])


#### nn.MaxPool2d
**池化层**

[https://www.jianshu.com/p/9d93a3391159](https://www.jianshu.com/p/9d93a3391159)


class torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False)  
**nn.Avg_pool**: 对于Avg_pool来说，参数和Max_pool是完全相同的，主要区别就是在kernel中取的是平均值操作。

参数：
- kernel_size(int or tuple): max pooling的窗口大小，
- stride(int or tuple, optional): max pooling的窗口移动的步长。默认值是kernel_size
- padding(int or tuple, optional): 输入的每一条边补充0的层数
- dilation(int or tuple, optional): 一个控制窗口中元素步幅的参数
- return_indices: 如果等于True，会返回输出最大值的序号，对于上采样操作会有帮助
- ceil_mode: 如果等于True，计算输出信号大小的时候，会使用向上取整，代替默认的向下取整的操作

[[back to top](#Sections)]

<img src="learn_img/16715697-3d69c563031e9ec4.webp" width="50%"/>

In [17]:
import torch
import torch.nn as nn
a = torch.randn(3,5,10)
b = nn.MaxPool2d((5,1))  # kernel = 5 步长为1
c = b(a)
c.shape

torch.Size([3, 1, 10])

In [18]:
# pool操作并不改变张量的通道数
x = torch.rand(1,3,7,7)
out = nn.MaxPool2d(kernel_size=2,stride=2)
out.forward(x).shape

torch.Size([1, 3, 3, 3])

In [21]:
x = torch.rand(1,3,7,7)
out = nn.AvgPool2d(kernel_size=2,stride=2)
out.forward(x).shape

torch.Size([1, 3, 3, 3])

#### nn.Linear
[https://blog.csdn.net/qq_42079689/article/details/102873766](https://blog.csdn.net/qq_42079689/article/details/102873766)  
更详细：[https://blog.csdn.net/weixin_44613063/article/details/90274590](https://blog.csdn.net/weixin_44613063/article/details/90274590)

PyTorch的 **nn.Linear()** 是用于设置网络中的全连接层的，需要注意的是全连接层的输入与输出都是二维张量，一般形状为\[batch_size, size\]
$$y=xA^T+b$$

计算步骤：
```python
@weak_script_method
def forward(self, input):
    return F.linear(input, self.weight, self.bias) 
```
返回的是：**input * weight + bias**

[[back to top](#Sections)]

In [24]:
import torch
from torch import nn

# in_features由输入张量的形状决定，out_features则决定了输出张量的形状 
connected_layer = nn.Linear(in_features = 64*64*3, out_features = 1)

# 假定输入的图像形状为[64,64,3]
input = torch.randn(1,64,64,3)

# 将四维张量转换为二维张量之后，才能作为全连接层的输入
input = input.view(1,64*64*3)
print(input.shape)
output = connected_layer(input) # 调用全连接层
print(output.shape)

torch.Size([1, 12288])
torch.Size([1, 1])


#### nn.ReLU&nbsp;vs&nbsp;F.ReLU
[https://blog.csdn.net/u011501388/article/details/86602275](https://blog.csdn.net/u011501388/article/details/86602275)

在如下网络中，AlexNet_1与AlexNet_2实现的结果是一致的，但是可以看到将ReLU层添加到网络有两种不同的实现，即nn.ReLU和F.ReLU两种实现方法。
其中nn.ReLU作为一个层结构，必须添加到nn.Module容器中才能使用，而F.ReLU则作为一个函数调用，看上去作为一个函数调用更方便更简洁。具体使用哪种方式，取决于编程风格。在PyTorch中,nn.X都有对应的函数版本F.X，但是并不是所有的F.X均可以用于forward或其它代码段中，因为当网络模型训练完毕时，在存储model时，在forward中的F.X函数中的参数是无法保存的。也就是说，在forward中，使用的F.X函数一般均没有状态参数，比如F.ReLU，F.avg_pool2d等，均没有参数，它们可以用在任何代码片段中。

[[back to top](#Sections)]

In [25]:
import torch.nn as nn
import torch.nn.functional as F
import torch.nn as nn
 
class AlexNet_1(nn.Module):
 
    def __init__(self, num_classes=n):
        super(AlexNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
         )
 
    def forward(self, x):
        x = self.features(x)
 
class AlexNet_2(nn.Module):
 
    def __init__(self, num_classes=n):
        super(AlexNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(64),
         )
 
    def forward(self, x):
        x = self.features(x)
        x = F.ReLU(x)

#### nn.functional

In [1]:
from torch.nn import functional as F
F.max_pool1d
F.affine_grid
F.grid_sample
F.log_softmax
F.nll_loss

- F.max_pool1d
- F.affine_grid  - 仿射网络
- [F.grid_sample](https://blog.csdn.net/Hansry/article/details/88870389)  - grid_sample其实就是实现了一个双线性插值的图片大小变换。
- F.log_softmax - 在数学上等价于log(softmax(x))
- F.nll_loss - 负对数似然损失
    - [Pytorch损失函数torch.nn.NLLLoss()详解](https://blog.csdn.net/Jeremy_lf/article/details/102725285)

[[back to top](#Sections)]

### 优化器库
[深度学习——优化器算法Optimizer详解（BGD、SGD、MBGD、Momentum、NAG、Adagrad、Adadelta、RMSprop、Adam）](https://www.cnblogs.com/guoyaohua/p/8542554.html)

在机器学习、深度学习中使用的优化算法除了常见的梯度下降，还有 Adadelta，Adagrad，RMSProp 等几种优化器

torch中的优化器库
```python
import torch.optim as optim
```


[[back to top](#Sections)]

In [10]:
import torch.optim as optim

<module 'torch.optim' from 'D:\\ProgramData\\Anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\optim\\__init__.py'>

#### optim.SGD()
[torch.optim.SGD()各参数的解释](https://www.cnblogs.com/peixu/p/13194328.html)

`torch.optim.SGD(params, lr=, momentum=0, dampening=0, weight_decay=0, nesterov=False)`

Nesterov动量基于On the importance of initialization and momentum in deep learning中的公式.  
**参数：**
- params (iterable) – 待优化参数的iterable或者是定义了参数组的dict
- lr (float) – 学习率
- momentum (float, 可选) – 动量因子（默认：0）
- weight_decay (float, 可选) – 权重衰减（L2惩罚）（默认：0）
- dampening (float, 可选) – 动量的抑制因子（默认：0）
- nesterov (bool, 可选) – 使用Nesterov动量（默认：False）

```python
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
optimizer.zero_grad()
loss_fn(model(input), target).backward()
optimizer.step()
```

[[back to top](#Sections)]

#### optim.lr_scheduler
**设置模型步长的库，可以使用函数优化步长**  
[pytorch中调整学习率: torch.optim.lr_scheduler](https://blog.csdn.net/Strive_For_Future/article/details/83213971)  

**.StepLR()**
`class torch.optim.lr_scheduler.StepLR(optimizer,step_size,gamma=0.1,last_epoch=-1)`  
设置每个参数组的学习率为$lr*\lambda^{n}$, $n=\frac{epoch}{step\_size}$,当last_epoch=-1时,令lr=lr  
参数:
- **optimizer**(Optimizer对象): 优化器
- **step_size**(整数类型): 调整学习率的步长,每过step_size次,更新一次学习率
- **gamma**(float 类型): 学习率下降的乘数因子
- **last_epoch**(int类型): 最后一次epoch的索引,默认为-1.

示例：
```python
>>> from torch.optim.lr_scheduler import StepLR
>>> # Assuming optimizer uses lr = 0.05 for all groups
>>> # lr = 0.05     if epoch < 30
>>> # lr = 0.005    if 30 <= epoch < 60
>>> # lr = 0.0005   if 60 <= epoch < 90
>>> # ...
>>> scheduler = StepLR(optimizer, step_size=30, gamma=0.1)
>>> for epoch in range(100):
>>>     scheduler.step()
>>>     train(...)
>>>     validate(...)
```

[[back to top](#Sections)]

#### .step()
[torch之optimizer.step() 和loss.backward()和scheduler.step()的关系与区别](https://blog.csdn.net/yangwangnndd/article/details/95622893)

**`optimizer.step()`** 是用来更新梯度的，将方向传播计算出的残差依据优化器更新到权重上。  
**`scheduler.step()`** 按照Pytorch的定义是用来更新优化器的学习率的，一般是按照epoch为单位进行更换，即多少个epoch后更换一次学习率。

[[back to top](#Sections)]

In [9]:
import torch
import torch.optim as optim
model = torch.nn.Linear(100, 1000)
optimizer = optim.SGD(model.parameters(), lr = 0.01, momentum = 0.9)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size = 100, gamma = 0.1)
# model = net.train(model, loss_function, optimizer, scheduler, num_epochs = 100)

## torchvision库

torchvision库简介（翻译）: [https://www.cnblogs.com/yjphhw/p/9773333.html](https://www.cnblogs.com/yjphhw/p/9773333.html)  
torchvision是独立于pytorch的关于图像操作的一些方便工具库。  
torchvision的详细介绍在：[https://pypi.org/project/torchvision/](https://pypi.org/project/torchvision/)  
torchvision主要包括一下几个包：  
- vision.datasets : 几个常用视觉数据集，可以下载和加载，这里主要的高级用法就是可以看源码如何自己写自己的Dataset的子类
- vision.models : 流行的模型，例如 AlexNet, VGG, ResNet和Densenet以及 与训练好的参数。
- vision.transforms : 常用的图像操作，例如：随机切割，旋转，数据类型转换，图像到tensor,numpy数组到tensor,tensor到图像等。
- vision.utils : 用于把形似 (3 x H x W) 的张量保存到硬盘中，给一个mini-batch的图像可以产生一个图像格网。

[[back to top](#Sections)]

### torchvision.datasets
数据集

### torchvision.models
[PyTorch源码解读之torchvision.models](https://blog.csdn.net/u014380165/article/details/79119664)

In [10]:
from torchvision import models

### torchvision.transforms

#### transforms.Compose()
**链式处理、流水线处理**，可以将多个数据操作集成在一块处理

[[back to top](#Sections)]

In [2]:
from torchvision import transforms
data_transforms = transforms.Compose([
    transforms.RandomResizedCrop(224), #随机裁剪一个area然后再resize
    transforms.RandomHorizontalFlip(), #随机水平翻转
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
data_transforms

Compose(
    RandomResizedCrop(size=(224, 224), scale=(0.08, 1.0), ratio=(0.75, 1.3333), interpolation=PIL.Image.BILINEAR)
    RandomHorizontalFlip(p=0.5)
    ToTensor()
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)

In [5]:
# 数据扩充和训练规范化
# 只需验证标准化
input_size = 224
data_transforms = {
    'train': transforms.Compose([
        transforms.RandomResizedCrop(input_size),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize(input_size),
        transforms.CenterCrop(input_size),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}
data_transforms

{'train': Compose(
     RandomResizedCrop(size=(224, 224), scale=(0.08, 1.0), ratio=(0.75, 1.3333), interpolation=PIL.Image.BILINEAR)
     RandomHorizontalFlip(p=0.5)
     ToTensor()
     Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
 ),
 'val': Compose(
     Resize(size=224, interpolation=PIL.Image.BILINEAR)
     CenterCrop(size=(224, 224))
     ToTensor()
     Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
 )}

#### transforms.ToTensor()
#### transforms.Normalize()

**数据归一化，标准化**  
[关于transforms.Normalize()函数](https://blog.csdn.net/jzwong/article/details/104272600)

```python
transforms.ToTensor(),  # 归一化
transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))  # 标准化
```
那transform.Normalize()是怎么工作的呢？以上面代码为例，ToTensor()能够把灰度范围从0-255变换到0-1之间，而后面的transform.Normalize()则把0-1变换到(-1,1).具体地说，对每个通道而言，Normalize执行以下操作：

[[back to top](#Sections)]

In [3]:
from torchvision import transforms
transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
transforms.ToTensor()

ToTensor()

## Bottom
[[back to top](#Sections)]