<font color=red>注：此处是文档第178页</font>

# PyTorch简介

# 1.Torch张量库介绍
深度学习的所有计算都是在张量上进行的,其中张量是一个可以被超过二维索引的矩阵的一般表示形式。稍后我们将详细讨论这意味着什么。首先，我们先来看一下我们可以用张量来干什么。

In [3]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

## 1.1 创建张量
张量可以在Python list形式下通过 torch.Tensor() 函数创建。

In [9]:
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.Tensor(M_data)
print(M)

T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


什么是三维张量？让我们这样想象。如果你有一个向量,那么对这个向量索引就会得到一个标量。如果你有一个矩阵，对这个矩阵索引那么就会得到一个向量。如果你有一个三维张量，那么对其索引就会得到一个矩阵!

针对术语的说明：当我在本教程内使用“`tensor`”，它针对的是所有 `torch.Tensor` 对象。矩阵和向量是特殊的 `torch.Tensors` ，他们的维度分别是1和2。当我说到三维张量，我会简洁的使用“`3Dtensor`”。

In [19]:
# 索引V得到一个标量（0维张量）
print(V[0])
# 从向量V中获取一个数字
print(V[0].item())
# 索引M得到一个向量
print(M[0])
# 索引T得到一个矩阵
print(T[0])
print(T[1,1])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])
tensor([7., 8.])


你也可以创建其他数据类型的tensors。默认的数据类型为浮点型。可以使用 `torch.LongTensor()`来创建一个整数类型的张量。你可以在文 件中寻找更多的数据类型，但是浮点型和长整形是最常用的。

你可以使用 `torch.randn()` 创建一个张量。这个张量拥有随机数据和需要指定的维度。

In [11]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


## 1.2 张量操作
你可以以你想要的方式操作张量。

In [12]:
x = torch.Tensor([1., 2., 3.])
y = torch.Tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


可以查阅[文档](https://pytorch.org/docs/torch.html)获取大量可用操作的完整列表,这些操作不仅局限于数学操作范围。

接下来一个很有帮助的操作就是连接。

In [21]:
# 默认情况下, 它沿着第一个行进行连接 (连接行)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(x_1)
print(y_1)
print(z_1)

tensor([[ 0.5438, -0.4057,  1.1341, -1.1115,  0.3501],
        [-0.7703, -0.1473,  0.6272,  1.0935,  0.0939]])
tensor([[ 1.2381, -1.3459,  0.5119, -0.6933, -0.1668],
        [-0.9999, -1.6476,  0.8098,  0.0554,  1.1340],
        [-0.5326,  0.6592, -1.5964, -0.3769, -3.1020]])
tensor([[ 0.5438, -0.4057,  1.1341, -1.1115,  0.3501],
        [-0.7703, -0.1473,  0.6272,  1.0935,  0.0939],
        [ 1.2381, -1.3459,  0.5119, -0.6933, -0.1668],
        [-0.9999, -1.6476,  0.8098,  0.0554,  1.1340],
        [-0.5326,  0.6592, -1.5964, -0.3769, -3.1020]])


In [23]:
# 连接列：
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# 第二个参数指定了沿着哪条轴连接
z_2 = torch.cat([x_2, y_2], dim=1)
print(x_2)
print(y_2)
print(z_2)
# 如果你的tensors是不兼容的，torch会报错。取消注释来查看错误。
# torch.cat([x_1, x_2])

tensor([[-0.6101, -1.2960, -0.9434],
        [ 0.6684,  1.1628, -0.3229]])
tensor([[ 1.8782, -0.5666,  0.4016, -0.1153,  0.3170],
        [ 0.5629,  0.8662, -0.3528,  0.3482,  1.1371]])
tensor([[-0.6101, -1.2960, -0.9434,  1.8782, -0.5666,  0.4016, -0.1153,  0.3170],
        [ 0.6684,  1.1628, -0.3229,  0.5629,  0.8662, -0.3528,  0.3482,  1.1371]])


## 1.3 重构张量
使用 `.view()` 去重构张量。这是一个高频方法，因为许多神经网络的神经元对输入格式有明确的要求。你通常需要先将数据重构再输入到神经元中。

In [26]:
x = torch.arange(24).view(2,3,4)
print(x)
print(x.view(2, 12)) # 重构为2行12列
# 同上。如果维度为-1,那么它的大小可以根据数据推断出来
print(x.view(2, -1))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
