### PyTorch与Numpy对比

PyTorch在很多地方个Numpy的接口是复用的，很多功能是相同的

In [11]:
import torch
import numpy as np

In [12]:
x1 = torch.rand(5, 3)
x2 = np.random.rand(5, 3)
print(x1)
print(x2)

tensor([[0.8669, 0.6390, 0.0863],
        [0.9445, 0.2415, 0.1976],
        [0.8671, 0.8852, 0.9535],
        [0.2973, 0.1353, 0.3188],
        [0.1053, 0.8379, 0.0275]])
[[0.33452849 0.28745964 0.98549192]
 [0.22180951 0.76181047 0.7729443 ]
 [0.33112425 0.80696619 0.60484499]
 [0.199937   0.78317782 0.56692856]
 [0.47441874 0.13841262 0.56787453]]


In [13]:
x1 = torch.empty(5, 3)
x2 = np.empty((5, 3))
print(x1)
print(x2)

tensor([[8.4490e-39, 1.1112e-38, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 9.6429e-39],
        [8.4490e-39, 1.0194e-38, 9.4592e-39],
        [1.0102e-38, 8.4490e-39, 8.9082e-39],
        [9.1837e-39, 9.2755e-39, 1.0561e-38]])
[[0.33452849 0.28745964 0.98549192]
 [0.22180951 0.76181047 0.7729443 ]
 [0.33112425 0.80696619 0.60484499]
 [0.199937   0.78317782 0.56692856]
 [0.47441874 0.13841262 0.56787453]]


In [14]:
x1 = torch.zeros(5, 3, dtype=torch.long)
x2 = np.zeros((5, 3), dtype=np.long)
print(x1)
print(x2)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
x1 = torch.tensor([5.5, 3])
x2 = np.array([5.5, 3])
print(x1)
print(x2)

tensor([5.5000, 3.0000])
[5.5 3. ]


In [16]:
x1 = x1.new_ones(5, 3, dtype=torch.double)
x2 = np.ones((5, 3), dtype=np.double)
print(x1)
print(x2)
x3 = torch.rand_like(x1, dtype=torch.float)
# result has the same size
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[0.6374, 0.1705, 0.1910],
        [0.8002, 0.6003, 0.7929],
        [0.7666, 0.8124, 0.0706],
        [0.8858, 0.7909, 0.9859],
        [0.6567, 0.6447, 0.2980]])


In [17]:
x5 = np.empty((5, 3))
x5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
print(x3.size())
print(x2.shape)

torch.Size([5, 3])
(5, 3)


In [19]:
y1 = torch.rand(5, 3)
y2 = np.random.random((5, 3))
print(y1)
print(y2)
print(x1 + y1)
print(x2 + y2)

tensor([[0.1976, 0.8181, 0.4691],
        [0.3095, 0.3127, 0.7401],
        [0.6208, 0.2282, 0.4034],
        [0.5537, 0.3822, 0.5394],
        [0.3444, 0.3849, 0.9218]])
[[0.64898746 0.41905018 0.94119331]
 [0.09773234 0.95719956 0.26480259]
 [0.84631353 0.27108646 0.90515135]
 [0.64692044 0.38943333 0.4687107 ]
 [0.45253273 0.02150717 0.87858582]]
tensor([[1.1976, 1.8181, 1.4691],
        [1.3095, 1.3127, 1.7401],
        [1.6208, 1.2282, 1.4034],
        [1.5537, 1.3822, 1.5394],
        [1.3444, 1.3849, 1.9218]], dtype=torch.float64)
[[1.64898746 1.41905018 1.94119331]
 [1.09773234 1.95719956 1.26480259]
 [1.84631353 1.27108646 1.90515135]
 [1.64692044 1.38943333 1.4687107 ]
 [1.45253273 1.02150717 1.87858582]]


In [20]:
print(torch.add(x1, y1))
print(np.add(x2, y2))

tensor([[1.1976, 1.8181, 1.4691],
        [1.3095, 1.3127, 1.7401],
        [1.6208, 1.2282, 1.4034],
        [1.5537, 1.3822, 1.5394],
        [1.3444, 1.3849, 1.9218]], dtype=torch.float64)
[[1.64898746 1.41905018 1.94119331]
 [1.09773234 1.95719956 1.26480259]
 [1.84631353 1.27108646 1.90515135]
 [1.64692044 1.38943333 1.4687107 ]
 [1.45253273 1.02150717 1.87858582]]


In [21]:
result1 = torch.empty(5, 3)
torch.add(x1, y1, out=result1)
print(result1)

result2 = np.empty((5, 3))
np.add(x2, y2, out=result2)
print(result2)

tensor([[1.1976, 1.8181, 1.4691],
        [1.3095, 1.3127, 1.7401],
        [1.6208, 1.2282, 1.4034],
        [1.5537, 1.3822, 1.5394],
        [1.3444, 1.3849, 1.9218]])
[[1.64898746 1.41905018 1.94119331]
 [1.09773234 1.95719956 1.26480259]
 [1.84631353 1.27108646 1.90515135]
 [1.64692044 1.38943333 1.4687107 ]
 [1.45253273 1.02150717 1.87858582]]


In [22]:
print(y1.add_(x1))

tensor([[1.1976, 1.8181, 1.4691],
        [1.3095, 1.3127, 1.7401],
        [1.6208, 1.2282, 1.4034],
        [1.5537, 1.3822, 1.5394],
        [1.3444, 1.3849, 1.9218]])


In [23]:
x1 = x1.new_empty(5, 3, dtype=torch.double)
x2 = np.empty((5, 3), dtype=np.double)
print(x1)
print(x2)

tensor([[4.8616e-321, 4.8616e-321, 4.6245e-321],
        [4.6245e-321, 4.8023e-321, 4.8023e-321],
        [4.7430e-321, 4.7430e-321, 4.2885e-321],
        [4.2885e-321, 5.5928e-321, 5.5928e-321],
        [2.5889e-321, 2.5889e-321, 4.9604e-321]], dtype=torch.float64)
[[1.64898746 1.41905018 1.94119331]
 [1.09773234 1.95719956 1.26480259]
 [1.84631353 1.27108646 1.90515135]
 [1.64692044 1.38943333 1.4687107 ]
 [1.45253273 1.02150717 1.87858582]]


In [24]:
print(y1.add_(x1))

tensor([[1.1976, 1.8181, 1.4691],
        [1.3095, 1.3127, 1.7401],
        [1.6208, 1.2282, 1.4034],
        [1.5537, 1.3822, 1.5394],
        [1.3444, 1.3849, 1.9218]])


In [25]:
print(x1[:, 1])
print(x2[:, 1])

tensor([4.8616e-321, 4.8023e-321, 4.7430e-321, 5.5928e-321, 2.5889e-321],
       dtype=torch.float64)
[1.41905018 1.95719956 1.27108646 1.38943333 1.02150717]


In [26]:
x1 = torch.randn(4, 4)
y1 = x1.view(16)
z1 = x1.view(-1, 8)  # the size -1 is inferred from other dimensions
x2 = np.random.randn(4, 4)
y2 = x2.reshape(16)
z2 = x2.reshape((-1, 8))  # 大小-1是从其他维度推断出来的
print(x1.size(), y1.size(), z1.size())
print(x2.shape, y2.shape, z2.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
(4, 4) (16,) (2, 8)


In [27]:
x1 = torch.randn(1)
y1 = torch.randn(4, 4)
x2 = np.random.randn(1)
y2 = np.random.randn(4, 4)
print(x1, x1.item(), y1[0, 0].item())
print(x2, x2[0], y2[0, 0])

tensor([0.3318]) 0.33180001378059387 -0.5695686936378479
[-1.93321368] -1.9332136848414154 -0.18143674488593461


#### 任何使张量会发生变化的操作都有一个前缀 

In [28]:
# pytorch的
x1 = torch.Tensor([[1,2,3,4], [5,6,7,8]])
y1 = torch.Tensor([[2,3,4,1], [6,7,8,5]])
print("x1", x1)
print("y1", y1)
print('---用y1覆盖x1------')
z1 = x1.copy_(y1)
print("x1", x1)
print("y1", y1)
print("z1", z1)

print('---修改参数,x1,y1互不影响,z1与x1是同一参数------')
x1[0,0] = 10
y1[0,1] = 20
z1[0,2] = 30
print("x1", x1)
print("y1", y1)
print("z1", z1)

x1.t_()
print(x1)

x1 tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
y1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
---用y1覆盖x1------
x1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
y1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
z1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
---修改参数,x1,y1互不影响,z1与x1是同一参数------
x1 tensor([[10.,  3., 30.,  1.],
        [ 6.,  7.,  8.,  5.]])
y1 tensor([[ 2., 20.,  4.,  1.],
        [ 6.,  7.,  8.,  5.]])
z1 tensor([[10.,  3., 30.,  1.],
        [ 6.,  7.,  8.,  5.]])
tensor([[10.,  6.],
        [ 3.,  7.],
        [30.,  8.],
        [ 1.,  5.]])


### PyTorch 自动微分

In [55]:
import torch

In [56]:
x1 = torch.ones(2, 2, requires_grad=True)
x2 = torch.ones(2, 2, requires_grad=False)
print(x1)
print(x2)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])


In [57]:
y1 = x1 + 2
y2 = x2 + 2
print(y1)
print(y2)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[3., 3.],
        [3., 3.]])


In [58]:
print(y1.grad_fn)
print(y2.grad_fn)

None


In [59]:
z1 = y1 * y1 * 3
z2 = y2 * y2 * 3

out1 = z1.mean()
out2 = z2.mean()

print(z1)
print(z2)
print(out1)
print(out2)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor([[27., 27.],
        [27., 27.]])
tensor(27., grad_fn=<MeanBackward0>)
tensor(27.)


.requires_grad_( … ) 会改变张量的 requires_grad 标记。输入的标记默认为 False ，如果没有提供
相应的参数。

In [60]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


梯度：

我们现在后向传播，因为输出包含了一个标量，out.backward() 等同于

out.backward(torch.tensor(1.))。

In [61]:
out1.backward()

打印梯度 d(out)/dx

In [62]:
print(x1.grad)
print(x2.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None


x1 = torch.ones(2, 2, requires_grad=True)  
y1 = x1 + 2  
z1 = y1 * y1 * 3  
out1 = z1.mean()  
此时对应公式：$$o = \frac{1}{4}\sum_{i}z_i$$
$$z_i=(3x + 2)^2$$

一个雅可比向量积的例子：

In [63]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ 282.7324, -164.1372, 1395.5574], grad_fn=<MulBackward0>)


In [64]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


你可以通过将代码包裹在 with torch.no_grad()，来停止对从跟踪历史中 的 .requires_grad=True 的
张量自动求导。

In [65]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
