### PyTorch与Numpy对比

PyTorch在很多地方个Numpy的接口是复用的，很多功能是相同的

In [4]:
import torch
import numpy as np

In [47]:
x1 = torch.rand(5, 3)
x2 = np.random.rand(5, 3)
print(x1)
print(x2)

tensor([[0.4114, 0.2761, 0.4594],
        [0.0359, 0.1541, 0.3638],
        [0.7446, 0.7419, 0.0747],
        [0.6547, 0.4000, 0.2273],
        [0.7493, 0.9523, 0.1496]])
[[0.70436684 0.00634363 0.07309778]
 [0.17712406 0.17935251 0.74888941]
 [0.90927267 0.68183032 0.20083544]
 [0.12932494 0.61726886 0.11800289]
 [0.19314692 0.51167789 0.12288183]]


In [48]:
x1 = torch.empty(5, 3)
x2 = np.empty((5, 3))
print(x1)
print(x2)

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38]])
[[0.70436684 0.00634363 0.07309778]
 [0.17712406 0.17935251 0.74888941]
 [0.90927267 0.68183032 0.20083544]
 [0.12932494 0.61726886 0.11800289]
 [0.19314692 0.51167789 0.12288183]]


In [25]:
x1 = torch.zeros(5, 3, dtype=torch.long)
x2 = np.zeros((5, 3), dtype=np.long)
print(x1)
print(x2)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
x1 = torch.tensor([5.5, 3])
x2 = np.array([5.5, 3])
print(x1)
print(x2)

tensor([5.5000, 3.0000])
[5.5 3. ]


In [59]:
x1 = x1.new_ones(5, 3, dtype=torch.double)
x2 = np.ones((5, 3), dtype=np.double)
print(x1)
print(x2)
x3 = torch.rand_like(x1, dtype=torch.float)
# result has the same size
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[0.8800, 0.7836, 0.4766],
        [0.4261, 0.3910, 0.6787],
        [0.0930, 0.8117, 0.8943],
        [0.7003, 0.7202, 0.4769],
        [0.7214, 0.4829, 0.6361]])


In [45]:
x5 = np.empty((5, 3))
x5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x1 = torch
x2 = np
print(x1)
print(x2)

In [62]:
print(x3.size())
print(x2.shape)

torch.Size([5, 3])
(5, 3)


In [65]:
y1 = torch.rand(5, 3)
y2 = np.random.random((5, 3))
print(y1)
print(y2)
print(x1 + y1)
print(x2 + y2)

tensor([[0.2089, 0.0689, 0.8483],
        [0.4483, 0.5105, 0.9504],
        [0.0529, 0.4283, 0.9449],
        [0.9011, 0.4982, 0.7698],
        [0.3762, 0.9745, 0.4631]])
[[0.66073628 0.26091117 0.32163709]
 [0.38813585 0.42579982 0.77179191]
 [0.17213077 0.66688412 0.51632484]
 [0.70402799 0.66865081 0.52534292]
 [0.51299403 0.22186785 0.25163922]]
tensor([[1.2089, 1.0689, 1.8483],
        [1.4483, 1.5105, 1.9504],
        [1.0529, 1.4283, 1.9449],
        [1.9011, 1.4982, 1.7698],
        [1.3762, 1.9745, 1.4631]], dtype=torch.float64)
[[1.66073628 1.26091117 1.32163709]
 [1.38813585 1.42579982 1.77179191]
 [1.17213077 1.66688412 1.51632484]
 [1.70402799 1.66865081 1.52534292]
 [1.51299403 1.22186785 1.25163922]]


In [67]:
print(torch.add(x1, y1))
print(np.add(x2, y2))

tensor([[1.2089, 1.0689, 1.8483],
        [1.4483, 1.5105, 1.9504],
        [1.0529, 1.4283, 1.9449],
        [1.9011, 1.4982, 1.7698],
        [1.3762, 1.9745, 1.4631]], dtype=torch.float64)
[[1.66073628 1.26091117 1.32163709]
 [1.38813585 1.42579982 1.77179191]
 [1.17213077 1.66688412 1.51632484]
 [1.70402799 1.66865081 1.52534292]
 [1.51299403 1.22186785 1.25163922]]


In [71]:
result1 = torch.empty(5, 3)
torch.add(x1, y1, out=result1)
print(result1)

result2 = np.empty((5, 3))
np.add(x2, y2, out=result2)
print(result2)

tensor([[1.2089, 1.0689, 1.8483],
        [1.4483, 1.5105, 1.9504],
        [1.0529, 1.4283, 1.9449],
        [1.9011, 1.4982, 1.7698],
        [1.3762, 1.9745, 1.4631]])
[[1.66073628 1.26091117 1.32163709]
 [1.38813585 1.42579982 1.77179191]
 [1.17213077 1.66688412 1.51632484]
 [1.70402799 1.66865081 1.52534292]
 [1.51299403 1.22186785 1.25163922]]


In [73]:
print(y1.add_(x1))

tensor([[2.2089, 2.0689, 2.8483],
        [2.4483, 2.5105, 2.9504],
        [2.0529, 2.4283, 2.9449],
        [2.9011, 2.4982, 2.7698],
        [2.3762, 2.9745, 2.4631]])


In [58]:
x1 = x1.new_empty(5, 3, dtype=torch.double)
x2 = np.empty((5, 3), dtype=np.double)
print(x1)
print(x2)

tensor([[2.5296e-321, 2.5296e-321, 3.9921e-321],
        [3.9921e-321, 2.3913e-321, 2.3913e-321],
        [4.8221e-321, 4.8221e-321, 5.2964e-321],
        [5.2964e-321, 5.2766e-321, 5.2766e-321],
        [5.7904e-321, 5.7904e-321, 5.8102e-321]], dtype=torch.float64)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [74]:
print(y1.add_(x1))

tensor([[3.2089, 3.0689, 3.8483],
        [3.4483, 3.5105, 3.9504],
        [3.0529, 3.4283, 3.9449],
        [3.9011, 3.4982, 3.7698],
        [3.3762, 3.9745, 3.4631]])


In [76]:
print(x1[:, 1])
print(x2[:, 1])

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]


In [93]:
x1 = torch.randn(4, 4)
y1 = x1.view(16)
z1 = x1.view(-1, 8)  # the size -1 is inferred from other dimensions
x2 = np.random.randn(4, 4)
y2 = x2.reshape(16)
z2 = x2.reshape((-1, 8))  # 大小-1是从其他维度推断出来的
print(x1.size(), y1.size(), z1.size())
print(x2.shape, y2.shape, z2.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
(4, 4) (16,) (2, 8)


In [104]:
x1 = torch.randn(1)
y1 = torch.randn(4, 4)
x2 = np.random.randn(1)
y2 = np.random.randn(4, 4)
print(x1, x1.item(), y1[0, 0].item())
print(x2, x2[0], y2[0, 0])

tensor([0.2306]) 0.23059606552124023 -0.8247631788253784
[-0.13179297] -0.13179296510994878 0.6916514836567711


#### 任何使张量会发生变化的操作都有一个前缀 

In [137]:
# pytorch的
x1 = torch.Tensor([[1,2,3,4], [5,6,7,8]])
y1 = torch.Tensor([[2,3,4,1], [6,7,8,5]])
print("x1", x1)
print("y1", y1)
print('---用y1覆盖x1------')
z1 = x1.copy_(y1)
print("x1", x1)
print("y1", y1)
print("z1", z1)

print('---修改参数,x1,y1互不影响,z1与x1是同一参数------')
x1[0,0] = 10
y1[0,1] = 20
z1[0,2] = 30
print("x1", x1)
print("y1", y1)
print("z1", z1)

x1.t_()
print(x1)

x1 tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
y1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
---用y1覆盖x1------
x1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
y1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
z1 tensor([[2., 3., 4., 1.],
        [6., 7., 8., 5.]])
---修改参数,x1,y1互不影响,z1与x1是同一参数------
x1 tensor([[10.,  3., 30.,  1.],
        [ 6.,  7.,  8.,  5.]])
y1 tensor([[ 2., 20.,  4.,  1.],
        [ 6.,  7.,  8.,  5.]])
z1 tensor([[10.,  3., 30.,  1.],
        [ 6.,  7.,  8.,  5.]])
tensor([[10.,  6.],
        [ 3.,  7.],
        [30.,  8.],
        [ 1.,  5.]])
